import React from "react";
import Head from "next/head";
import NavDesktop from "./NavDesktop";
import useWindowSize from "../hooks/useWindowSize";
import NavMobile from "./NavMobile";
import Footer from "./Footer";

const Layout = ({ children }) => {
  const { width } = useWindowSize();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {width > 520 ? <NavDesktop /> : <NavMobile />}
      {children}
      <Footer />
    </>
  );
};

export default Layout;
