import React from "react";
import Head from "next/head";
import Navbar from "./Navbar";
import { useWindowSize } from "@react-hook/window-size";
import Footer from "./Footer";

const Layout = ({ children }) => {
  const [width] = useWindowSize();
  return (
    <>
      <Head>
        <title>Natasha Villamizar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {children}
      <Footer />
    </>
  );
};

export default Layout;
